const Data = [
  {
    id: 1,
    category: "Food",
    date: "05 Feb,2023",
    amount: "$200",
    invoiceNumber: "ADES32145",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Approved",
    action: "cancel",
  },
  {
    id: 2,
    category: "Bike",
    date: "05 Feb,2023",
    amount: "$100",
    invoiceNumber: "ADES32146",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Approved",
    action: "cancel",
  },
  {
    id: 3,
    category: "Food",
    date: "05 May,2023",
    amount: "$600",
    invoiceNumber: "ADES32147",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Rejected",
    action: "cancel",
  },
  {
    id: 4,
    category: "food",
    date: "05 Dec,2023",
    amount: "$500",
    invoiceNumber: "ADES32148",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Waiting For Approval",
    action: "cancel",
  },
  {
    id: 5,
    category: "Travel",
    date: "05 Jan,2023",
    amount: "$200",
    invoiceNumber: "ADES32149",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Rejected",
    action: "cancel",
  },
  {
    id: 6,
    category: "Snaks",
    date: "05 Feb,2023",
    amount: "$200",
    invoiceNumber: "ADES32144",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Approved",
    action: "cancel",
  },
  {
    id: 7,
    category: "Dress",
    date: "05 Mar,2023",
    amount: "$200",
    invoiceNumber: "ADES32143",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Waiting For Approval",
    action: "cancel",
  },
  {
    id: 8,
    category: "Car",
    date: "05 Apr,2023",
    amount: "$200",
    invoiceNumber: "ADES32142",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    status: "Waiting For Approval",
    action: "cancel",
  },
];
export default Data;
